version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hapasat
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_PATH: /app/data/hapasat.db
      OPENSAT_API_URL: https://api.jsonsilo.com/public/942c3c3b-3a0c-4be3-81c2-12029def19f5
      BACKEND_URL: http://localhost:3001/api
      FRONTEND_URL: http://localhost:3000
      JWT_SECRET: change-me-in-production
    volumes:
      - ./data:/app/data

volumes:
  data:
